### PR TITLE
Chern number

### PR DESCRIPTION
**Pull request by Nastaran-Salehi**
Dear Anders and Johan,

In order to make it easier to review the changes that we have made in Multiscale and Chern number subroutines, I have divided them into two branches.
The previous error that I had in GitHub compilations is not occurring on my laptop, and the "chern_number.mod" file is generated.
Also, about the subroutine "calculate_eigenvector()", we want to keep it for the time being because we will modify it in the future to add more topological properties, so that the subroutine will be quite different from the one in diamag.f90.

Best regards,
Nastaran

### CODE REVIEW

**Comment by anbergman** [comment]
Also, I forgot to add but very nice with the example and thanks for splitting the PR into Chern and MS parts!

**Comment by Nastaran-Salehi** [comment]
Hi Anders,

Thank you for your review and comment!
Your mentioned points will be properly addressed in the next commit.

Best regards,
Nastaran

**Review by anbergman — APPROVED** [review]
The additions look much better now when the code duplication is gone.
There is still some doubts about the eigenvector arrays belonging to one module but being allocated and used in another. However, I think this can be fixed in the code post-merge.  
It does not seem as any tests have been added from this functionality. This can be also be addressed post-merge but should not be forgotten. 
Good job overall!

**Comment by anbergman** [comment]
Looks good now!
We should still consider some rewrites regarding modularity and efficiency but that can be done at a later stage.

**Comment by Nastaran-Salehi** [comment]
Nice to see this pull request has been successfully merged! I appreciate your review and comment!
There is a test for Chern number calculation in: example/SpinWaves/Kagome_ChernNumber .
I will keep in mind your notes regarding modularity and efficiency!
Thank you very much!

**Pull request merged**
