### PR TITLE
Re-activated legacy temperature gradient behaviour

### PR DESCRIPTION
**Pull request by anbergman**
This is a semi-temporary fix to reinstate the original temperature gradient functionality, originally implemented by @JPchico .

This functionality has since its introduction been replaced by extended and improved functionalities for both spatially dependent and time-dependent temperature profiles, also by @JPchico (see `setup_temp()` and related routines).  There is however a lack of working examples (and tests) for these routines so while waiting for an overhaul of these routines, the legacy gradient functionality could be useful.

Example is available at `examples/SpecialFeatures/TemperatureGradient`. No test has been added

### CODE REVIEW

**Review by JPchico — COMMENTED** [review]
This looks good. I have to admit that I do not remember anymore how much of this used to work, but the changes seem minimal.
The call to setup the site temperature seems to be commented out, so are we really even using the temperature gradient in this case? It seems to be in the thermalization step so maybe it does not matter but it seems a bit strange.

I would just say that the best would be to remove the unused commented out code and check if one needs the commented out  `SETUP_TEMP` subroutine call in the `uppasd.f90` .

**Comment by anbergman** [comment]
Thanks for the comments @JPchico! 
- The "legacy" routines do not need any inital grid setup. Reading the boundary conditions with `read_temperature_legacy`  is  enough for `Lparray()` and `lpfunction()` to do their thing. 
- From a code quality standpoint I agree that the best would be to remove the commented lines. But I feel that removing the commented calls/unussed functions here would reduce the chance of the newer and better temperature routines being revived even further. Another possibility would be to keep  the "newer" routines and their calls for `grad Y` and `grad F` and add a `grad L`  for the legacy approach. The drawback then would be to have doubled functionality with unverified quality.

**Comment by JPchico** [comment]
Fair enough, I think that a set of tests might be good to add, otherwise I think it can be merged.

**Review by JPchico — APPROVED** [review]

**Comment by anbergman** [comment]
Good! A test (or more) will be added at a later stage.

**Pull request merged**
